deprecated.vars.var1=a
deprecated.vars.var2=12
deprecated.vars.var3=13
deprecated.vars.var4=14
derecated.record.vars.var1=b
derecated.record.vars.var2=22
derecated.record.vars.var3=23
derecated.record.vars.var4=24